export const THEME = {
  colors: {
    primary: '#FF5722', // GrabnBite signature vibrant food orange
    primaryDark: '#E64A19',
    primaryLight: '#FFF1ED',
    primarySubtle: '#FFF7F4',
    secondary: '#1E293B',
    success: '#10B981',
    successLight: '#ECFDF5',
    warning: '#F59E0B',
    warningLight: '#FFFBEB',
    info: '#3B82F6',
    infoLight: '#EFF6FF',
    danger: '#EF4444',
    dangerLight: '#FEF2F2',
    background: '#F8F9FA',
    surface: '#FFFFFF',
    surfaceSubtle: '#F3F4F6',
    border: '#E5E7EB',
    borderLight: '#F3F4F6',
    text: '#111827',
    textPrimary: '#111827',
    textSecondary: '#4B5563',
    textTertiary: '#9CA3AF',
    textMuted: '#9CA3AF',
    textInverse: '#FFFFFF',
    overlay: 'rgba(0, 0, 0, 0.5)',
    star: '#F59E0B',
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 20,
    xxl: 24,
    hero: 32,
  },
  radii: {
    sm: 8,
    md: 12,
    lg: 16,
    xl: 20,
    full: 9999,
  },
  typography: {
    headingLg: {
      fontSize: 22,
      fontWeight: '700' as const,
      color: '#111827',
    },
    headingMd: {
      fontSize: 18,
      fontWeight: '700' as const,
      color: '#111827',
    },
    headingSm: {
      fontSize: 15,
      fontWeight: '600' as const,
      color: '#111827',
    },
    body: {
      fontSize: 14,
      color: '#374151',
    },
    bodySm: {
      fontSize: 12,
      color: '#6B7280',
    },
    caption: {
      fontSize: 11,
      color: '#9CA3AF',
    },
    button: {
      fontSize: 15,
      fontWeight: '700' as const,
      color: '#FFFFFF',
    },
  },
  shadows: {
    card: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.05,
      shadowRadius: 6,
      elevation: 2,
    },
    bottomBar: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: -3 },
      shadowOpacity: 0.06,
      shadowRadius: 8,
      elevation: 8,
    },
    modal: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.15,
      shadowRadius: 16,
      elevation: 10,
    },
  },
};
